### ISSUE TITLE
.NET crypto got killed, and maybe some app with crypto library too.

### ISSUE THREAD

**Issue by Bang1338** [LeDragoX/Win-Debloat-Tools#130]
### Describe the Bug

In `Optimize-Security.ps1`, or maybe somewhere else.
after Enabling .NET strong cryptography and other crypto related stuff, some installer like Discord failed to install.

![image](https://github.com/LeDragoX/Win-Debloat-Tools/assets/75790567/38af35eb-8fe3-46d0-8002-cc43804bdfae)

### How can this issue be reproduced?

Just press apply tweak in the GUI.

### Expected behavior?

N/A

### Operating System

Windows 10

### Operating System Version

20H2

### Logs

WDT: no log
Discord (log from error):
```log
...
1896> 2023-10-15 20:45:09> Program: Starting Squirrel Updater: --install .
1896> 2023-10-15 20:45:10> Program: Starting install, writing to C:\Users\Admin\AppData\Local\SquirrelTemp
1896> 2023-10-15 20:45:10> Program: About to install to: C:\Users\Admin\AppData\Local\Discord
1896> 2023-10-15 20:45:10> Program: Install path C:\Users\Admin\AppData\Local\Discord already exists, burning it to the ground
1896> 2023-10-15 20:45:10> IEnableLogger: Failed to remove existing directory on full install, is the app still running???: System.Security.Cryptography.CryptographicException: The keyset is not defined.

   at System.Security.Cryptography.CryptographicException.ThrowCryptographicException(Int32 hr)
   at System.Security.Cryptography.Utils._AcquireCSP(CspParameters param, SafeProvHandle& hProv)
   at System.Security.Cryptography.Utils.AcquireProvHandle(CspParameters parameters)
   at System.Security.Cryptography.Utils.get_StaticProvHandle()
   at System.IO.Path.GetRandomFileName()
   at Squirrel.Utility.<DeleteDirectory>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<LogIfThrows>d__37.MoveNext()
1896> 2023-10-15 20:45:10> Unhandled exception: System.AggregateException: One or more errors occurred. ---> System.Security.Cryptography.CryptographicException: The keyset is not defined.

   at System.Security.Cryptography.CryptographicException.ThrowCryptographicException(Int32 hr)
   at System.Security.Cryptography.Utils._AcquireCSP(CspParameters param, SafeProvHandle& hProv)
   at System.Security.Cryptography.Utils.AcquireProvHandle(CspParameters parameters)
   at System.Security.Cryptography.Utils.get_StaticProvHandle()
   at System.IO.Path.GetRandomFileName()
   at Squirrel.Utility.<DeleteDirectory>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<LogIfThrows>d__37.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Update.Program.<Install>d__5.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Squirrel.Update.Program.executeCommandLine(String[] args)
   at Squirrel.Update.Program.main(String[] args)
---> (Inner Exception #0) System.Security.Cryptography.CryptographicException: The keyset is not defined.

   at System.Security.Cryptography.CryptographicException.ThrowCryptographicException(Int32 hr)
   at System.Security.Cryptography.Utils._AcquireCSP(CspParameters param, SafeProvHandle& hProv)
   at System.Security.Cryptography.Utils.AcquireProvHandle(CspParameters parameters)
   at System.Security.Cryptography.Utils.get_StaticProvHandle()
   at System.IO.Path.GetRandomFileName()
   at Squirrel.Utility.<DeleteDirectory>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<LogIfThrows>d__37.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Update.Program.<Install>d__5.MoveNext()<---

```

# UPDATE BUG 16-10-23 4:00PM
Any .NET app that using crypto library also got killed.
Example `checksum.exe` from `choco`

![image](https://github.com/LeDragoX/Win-Debloat-Tools/assets/75790567/ec99b80e-668a-46d7-9896-994ba56dfb71)

# UPDATE BUG 16-10-23 4:07PM
Some C++ app also crashed. Including Kaspersky Plus which almost killed my PC and KPM
![image](https://github.com/LeDragoX/Win-Debloat-Tools/assets/75790567/09b398e4-1cd7-4938-b1b9-647667634cfa)

Same thing with Zoom x86 installer (but work for x64)
Image bellow is x86 installer
![image](https://github.com/LeDragoX/Win-Debloat-Tools/assets/75790567/5d7db08c-77ac-4943-aae8-078957323323)

# UPDATE BUG 17-10-23 8:50PM
Starting Cobalt Strike 4.9 (Java) also crash
![image](https://github.com/LeDragoX/Win-Debloat-Tools/assets/75790567/f085645c-e480-416d-8eec-5d74f4e34510)

# UPDATE BUG 17-10-23 9:35PM
I'm not sure why, but I think Crypto API got a problem by tweak.

# Update issues 15-11-23 16:12PM
Windows 10, not Windows 11, oops.
Also, sadly that I manually fix without you and caused BSod, restore point also overwritten

Rest In Peace, 128GB SSD, which had incoming Discord bot.
![image](https://cdn.discordapp.com/attachments/779629784509579288/1174275847096639568/rn_image_picker_lib_temp_7ca2b7c0-b97b-4285-bbce-7dbcb9da1e35.jpg)

**Comment by Bang1338** [comment]
^ typo mistake :/

**Comment by LeDragoX** [comment]
Okay, this seems to cause more trouble than help. I'm removing this from the script, but for newer versions.
All users still need to remove it manually, with this command on PowerShell:
```ps1
Remove-ItemProperty -Path "HKLM:\SOFTWARE\Microsoft\.NETFramework\v4.0.30319" -Name "SchUseStrongCrypto"
Remove-ItemProperty -Path "HKLM:\SOFTWARE\Wow6432Node\Microsoft\.NETFramework\v4.0.30319" -Name "SchUseStrongCrypto"
```
